create table if not exists public.carelotto_purchases (
  id bigint generated by default as identity primary key,
  ticket_number integer not null,
  round_id integer not null,
  payout_wallet text not null,
  art_id text not null,
  art_title text not null,
  buyer_email text,
  cause text not null,
  world_proof text,
  payment_method text not null,
  total integer not null default 3,
  artist integer not null default 1,
  cause_share integer not null default 1,
  lottery integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.carelotto_lottery_rounds (
  id integer primary key,
  status text not null default 'open',
  winner_request text not null default 'not_requested',
  vrf_request_id text,
  chainlink_tx_hash text,
  random_word text,
  winning_entry jsonb,
  prize_claim_status text not null default 'not_ready',
  updated_at timestamptz not null default now()
);

alter table public.carelotto_purchases enable row level security;
alter table public.carelotto_lottery_rounds enable row level security;

drop policy if exists "CareLotto purchases are readable" on public.carelotto_purchases;
create policy "CareLotto purchases are readable"
on public.carelotto_purchases
for select
to anon, authenticated
using (true);

drop policy if exists "CareLotto purchases can be recorded" on public.carelotto_purchases;
create policy "CareLotto purchases can be recorded"
on public.carelotto_purchases
for insert
to anon, authenticated
with check (true);

drop policy if exists "CareLotto rounds are readable" on public.carelotto_lottery_rounds;
create policy "CareLotto rounds are readable"
on public.carelotto_lottery_rounds
for select
to anon, authenticated
using (true);

drop policy if exists "CareLotto rounds can be created" on public.carelotto_lottery_rounds;
create policy "CareLotto rounds can be created"
on public.carelotto_lottery_rounds
for insert
to anon, authenticated
with check (true);

drop policy if exists "CareLotto rounds can be updated" on public.carelotto_lottery_rounds;
create policy "CareLotto rounds can be updated"
on public.carelotto_lottery_rounds
for update
to anon, authenticated
using (true)
with check (true);

grant select, insert on public.carelotto_purchases to anon, authenticated;
grant select, insert, update on public.carelotto_lottery_rounds to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
